# -*- coding: utf-8 -*-
"""Biological Sequence Alignmment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AvWzJKBqCJaql1xnqsH-4hkvKKmo2-Bk
"""

import numpy as np

pt ={'match': 2, 'mismatch': -1, 'gap_penalty': -8}

def matches(a, b):
    if a == b:
        return pt['match']
    elif a == '-' or b == '-':
        return pt['gap_penalty']
    else:
        return pt['mismatch']

def needle_wunsch(s1, s2):
    m, n = len(s1), len(s2)

    H = np.zeros((m+1, n+1))    
    T = np.zeros((m+1, n+1))


    score = 0
    for x in range(1, m + 1):
        for y in range(1, n + 1):
            sc_diag = H[x-1][y-1] + matches(s1[x-1], s2[y-1])
            sc_up = H[x][y-1] + pt['gap_penalty']
            sc_left = H[x-1][y] + pt['gap_penalty']
            
            H[x][y] = max(0,sc_left, sc_up, sc_diag)
            if H[x][y] == 0: T[x][y] = 0
            if H[x][y] == sc_left: T[x][y] = 1
            if H[x][y] == sc_up: T[x][y] = 2
            if H[x][y] == sc_diag: T[x][y] = 3
            if H[x][y] >= score:
                max_x = x
                max_y = y
                score = H[x][y];
    

    alignment1, alignment2 = '', ''
 
    while T[x][y] != 0:
        if T[x][y] == 3:
            a1 = s1[x-1]
            a2 = s2[y-1]
            x -= 1
            y -= 1
        elif T[x][y] == 2:
            a1 = '-'  
            a2 = s2[y-1]
            y -= 1
        elif T[x][y] == 1:
            a1 = s1[x-1]
            a2 = '-'
            x -= 1
        alignment1 += a1
        alignment2 += a2

    alignment1 = alignment1[::-1]
    alignment2 = alignment2[::-1]
   

    print('Score =', score)
    print(alignment1)
    print(alignment2)


needle_wunsch('ANRGDFS','ANREFS')

